'use strict';

import customGsap from './modules/gsap';
import counter from './modules/counter';
import Animations from './modules/animations';
import Scroll from './modules/scroll';
import Menu from './modules/menu';
import customSlick from './modules/customSlick';
import filterCategory from './modules/filterCategory';
import uiAccordion from './modules/accordion';
import teamPage from './modules/team';
import searchFeild from './modules/search';
import tabFilter from './modules/tabs-filter';
import modal from './modules/modal';
import modalChart from './modules/modalChart';
import magnificPopup from './modules/magnificPopup';
import ourJourney from './modules/ourJourney';
import testimonialSlider from './modules/testimonialSlider';
import Effects from './modules/effects';
import progress from './modules/progress';
import share from './modules/share';
import howitWorks from './modules/howitWorks';
import exploreSlick from './modules/exploreSlick';
import ComparisonSlick from './modules/tableComparisonSlick';
import beyond from './modules/beyond-script';
import CompareSlick from './modules/tableCompareSlick';
import pdetailtabs from './modules/pdetailtabs';
import { spyScroll } from './modules/spyScroll';
import { numberInput } from './modules/numberInput';
import adsensebar from './modules/adsensebar';
import modalBookai from './modules/modalBookai';
import { scrollnav } from './modules/scrollnav';
import { scrollnavline } from './modules/scrollnavline';
import { dashboard } from './modules/dashborad';

(function () {
  customGsap.init();
  counter.init();
  progress.init();
  Effects.init();
  Animations.init();
  Menu.init();
  customSlick.init();
  filterCategory.init();
  uiAccordion.init();
  teamPage.init();
  searchFeild.init();
  tabFilter.init();
  modal.init();
  magnificPopup.init();
  ourJourney.init();
  testimonialSlider.init();
  share.init();
  howitWorks.init();
  exploreSlick.init();
  ComparisonSlick.init();
  CompareSlick.init();
  pdetailtabs.init();

  beyond.init();
  spyScroll.init();
  numberInput();
  adsensebar.init();
  modalChart.init();
  modalBookai.init();
  scrollnavline.init();
  dashboard.init();
})();
let scrolled = window.scrollY;
window.addEventListener('scroll', function () {
  scrolled = window.scrollY;
  Scroll.handle(scrolled);
  Animations.handle(scrolled, Scroll.direction);
});
window.addEventListener('load', function () {
  scrollnav.init();
});
